app/blueprints/auth.py
import os
from urllib.parse import urlencode

import requests
from flask import (
    Blueprint,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from app.appctx import exception, get_app, warning
from app.services import exchange_code, get_progress, sync_progress

auth_bp = Blueprint("auth", __name__)


@auth_bp.route("/pre-login")
def pre_login():
    """Render the pre-login page.
    Returns:
        Rendered login template with user image.
    """
    user = get_progress()
    template = "logout.html" if "user_data" in session else "login.html"
    return render_template(template, img=user["img"], year=session["year"])


@auth_bp.route("/login")
def login():
    """Redirect the user to Discord's OAuth2 authorization page.
    Returns:
        Redirect to Discord authorization URL.
    """
    params = {
        "client_id": os.getenv("DISCORD_CLIENT_ID"),
        "redirect_uri": os.getenv("DISCORD_REDIRECT_URI"),
        "response_type": "code",
        "scope": "identify guilds.members.read guilds.join",
    }
    return redirect(f"https://discord.com/api/oauth2/authorize?{urlencode(params)}")


@auth_bp.route("/callback")
def callback():
    """Handle the callback from Discord after user authorization.
    Returns:
        Redirect to the index page or error message.
        or Error message with HTTP status code 400.
    """
    print("\n\nin callback\n\n")
    if request.args.get("error"):
        exception(f"Request Error (/callback): {request.args}")
        return redirect(url_for("main.index"))

    if not (code := request.args.get("code")):
        return "Error: No code provided", 400

    token_response = exchange_code(code)
    token = token_response.get("access_token")
    if not token:
        warning(f"Token exchange failed: {token_response}")
        return "Error: No token received", 400

    session["token"] = token

    headers = {"Authorization": f"Bearer {token}"}
    response = requests.get("https://discord.com/api/users/@me", headers=headers)
    if response.status_code != 200:
        return "Error: No Response", 400

    if not (user_data := response.json()):
        return "Error: No user data received", 400
    session["user_data"] = user_data

    # Get Discord profile picture for user
    user_id = user_data["id"]
    avatar_hash = user_data["avatar"]
    avatar_url = "images/no_img.png"
    if avatar_hash:
        file_type = ["png", "gif"][avatar_hash.startswith("a_")]
        avatar_url = (
            f"https://cdn.discordapp.com/avatars/{user_id}/{avatar_hash}.{file_type}"
        )
    session["user_data"]["img"] = avatar_url

    # Add to database if not present
    progress = get_app().data_cache.load_progress(session["year"], user_id)
    print(f"\n\n{progress}\n\n")
    if not progress:
        added = get_app().data_cache.add_user(
            session["user_data"]["id"], session["user_data"]["username"]
        )
        if not added:
            return redirect(url_for("auth.logout"))
    sync_progress(session["year"], user_id)

    return redirect(url_for("main.index"))


@auth_bp.route("/logout")
def logout():
    """Log out the user by clearing the session.
    Returns:
        Redirect to the index page.
    """
    session.clear()
    return redirect(url_for("main.index"))

app/blueprints/challenge.py
import requests
from flask import (
    Blueprint,
    make_response,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from app.appctx import get_app
from app.services import get_progress, set_progress

challenge_bp = Blueprint("challenge", __name__)


def fix_static(txt: str) -> str:
    """Replace the "__STATIC__" placeholder in the html
    with the path to the static directory.
    Args:
        txt (str): Raw html text
    Returns:
        str: html text with the correct path for images and files
    """
    return txt.replace("__STATIC__", url_for("static", filename=""))


@challenge_bp.route("/challenge/<year>/<obs_num>", methods=["GET", "POST"])
def challenge(year: str, obs_num: str):
    """Render the challenge page for a specific challenge week number.
    Args:
        year (str): The desired year.
        obs_num (str): The obfuscated challenge number.
    Returns:
        Rendered challenge.html template or error message.
        or redirect to the challenge page on correct guess.
    """
    session["year"] = year
    app = get_app()
    num = int(app.data_cache.admin.html_nums[year][obs_num])
    error = None

    if request.method == "POST":
        guesses = [request.form.get(f"answer{i}", None) for i in (1, 2)]
        solutions = app.data_cache.html.solutions[year][num]
        for n, guess in enumerate(guesses):
            if (
                guess
                and guess.replace("_", " ").upper().strip() == solutions[f"part{n + 1}"]
            ):
                cookie = set_progress(num, n)
                resp = make_response(
                    redirect(url_for("challenge.challenge", year=year, obs_num=obs_num))
                )
                if cookie:
                    resp.set_cookie(cookie, f"{num}{'AB'[n]}")
                return resp
            else:
                error = "Incorrect. Please try again."

    user = get_progress()
    progress = user["progress"][f"c{num}"]
    html = app.data_cache.html.html.get(year, {}).get(num, {})
    parts = []
    for part_num in (1, 2):
        part_data = html.get(part_num)
        if not isinstance(part_data, dict):
            return redirect(url_for("main.index"))
        parts.append(
            {
                k: fix_static(v) if isinstance(v, str) else v
                for k, v in part_data.items()
            }
        )
    a, b = parts

    params = {
        "img": user["img"],
        "year": session["year"],
        "num": f"{num}",
        "a": a,
        "b": b,
        "sol1": a["solution"] if progress[0] else a["form"],
        "sol2": b["solution"] if progress[1] else b["form"],
        "part_two": progress[0],
        "done": progress[1] and "user_data" in session,
        "error": error,
    }
    return render_template("challenge.html", **params)


@challenge_bp.route("/access", methods=["POST"])
def access():
    """Grant access to a user and assign roles in Discord.

    Returns:
        Rendered link_complete.html template or error message.
        or Error message with HTTP status code.
    """
    app = get_app()
    bot_token = app.config["DISCORD_BOT_TOKEN"]
    year = session["year"]
    if not bot_token:
        return "Error: Bot token not found", 500

    num = int(app.data_cache.admin.obfuscations[year][f"{request.form.get('num')}"])

    guild_id = app.data_cache.admin.discord_ids["0"]["guild"]
    user_id = session["user_data"]["id"]
    channel_id = app.data_cache.admin.discord_ids[year][f"{num}"]
    print(
        f"{app.data_cache.admin.discord_ids[year]=} {num=} {app.data_cache.admin.discord_ids[year][f'{num}']=}"
    )
    verified_role = app.data_cache.admin.discord_ids["0"]["role"]

    headers = {"Authorization": f"Bot {bot_token}", "Content-Type": "application/json"}
    url = f"https://discord.com/api/v9/guilds/{guild_id}/members/{user_id}"
    response = requests.get(url, headers=headers)

    # User is not a member of the guild, add them
    if response.status_code == 404:
        payload = {"access_token": session["token"]}
        try:
            response = requests.put(url, headers=headers, json=payload)
            response.raise_for_status()
        except requests.exceptions.RequestException as e:
            print(f"Error: {e}")
            return f"Error: Failed to assign role: {response.text}", 400
        url += f"/roles/{verified_role}"
        try:
            response = requests.put(url, headers=headers)
            response.raise_for_status()
        except requests.exceptions.RequestException as e:
            return f"Error: {e}", 400
        else:
            if response.status_code != 204:
                return f"Error: Failed to assign role: {response.text}", 400

    content = (
        f"<@{user_id}> solved week {num}! If you'd like, "
        "please share how you arrived at the correct answer!"
    )
    url = f"https://discord.com/api/v9/channels/{channel_id}/thread-members/{user_id}"
    response = requests.get(url, headers=headers)

    if response.status_code != 200:
        url = f"https://discord.com/api/v9/channels/{channel_id}/messages"
        try:
            response = requests.post(url, headers=headers, json={"content": content})
            response.raise_for_status()
        except requests.exceptions.RequestException as e:
            return f"Error: {e}", 400
        else:
            if response.status_code != 200:
                return f"Error: Failed to send message: {response.text}", 400

    user = get_progress()
    egg = app.data_cache.html.html[year][num]["ee"]

    return render_template(
        "link_complete.html",
        year=year,
        img=user["img"],
        num=num,
        guild=guild_id,
        channel=channel_id,
        egg=egg,
    )

app/templates/challenge.html
{% extends "challenge_default.html" %}

{% block subtitle1 %}Part One:<br>{{ a["title"] }}{% endblock %}
{% block section1 %} {{ a["content"]|safe }} {% endblock %}
{% block intro1 %} {{ a["instructions"]|safe }} {% endblock %}
{% set input_url1 = url_for(
'static', filename="puzzle_input/" ~ year ~ "/" ~ num.zfill(2) ~ "/input1." ~ a.input
) %}
{% block solution1 %} {{sol1|safe }} {% endblock %}


{% if part_two %}
{% block subtitle2 %}Part Two:<br>{{ b["title"] }}{% endblock %}
{% block section2 %} {{ b["content"]|safe }} {% endblock %}
{% block intro2 %} {{ b["instructions"]|safe }} {% endblock %}
{% set input_url2 = url_for(
'static', filename="puzzle_input/" ~ year ~ "/" ~ num.zfill(2) ~ "/input2." ~ b.input_type
) %}
{% block solution2 %} {{sol2|safe }} {% endblock %}
{% endif %}

app/templates/challenge_default.html
{% extends "default.html" %}

{% block title %} Challenge # {{ num }} {% endblock %}

{% block main %}
{% if error %}
<dialog id="incorrect">
    <p>{{ error }}</p>
    <form method="dialog">
        <button>OK</button>
    </form>
</dialog>
<script>
    const dialog = document.getElementById("incorrect");
    dialog.showModal();
</script>
{% endif %}

<section class="section" id="part-one">
    <div class="header">
        <h2>{% block subtitle1 %}{% endblock %}</h2>
    </div>
    {% block section1 %} {% endblock %}
    <h4 class="main">{% block intro1 %}{% endblock %}</h4>
    <a id="a"></a>
    <div class="input">
        <a href="{{ input_url1 }}" class="input">
            <p class="main lg">[ click to get input ]</p>
        </a>
    </div>
    <div class="shimmer{% if part_two %} short{% endif %}">
        <form action="#a" method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="form-box">{% block solution1 %}{% endblock %}</div>
        </form>
    </div>
</section>

{% if part_two %}
<section class="section" id="part-two">
    <div class="header">
        <h2>{% block subtitle2 %}{% endblock %}</h2>
    </div>
    {% block section2 %}{% endblock %}
    <p class="main">{% block intro2 %}{% endblock %}</p>
    <a id="b"></a>
    <div class="input">
        <a href="{{ input_url2 }}" class="input">
            <p class="main lg">[ click to get input ]</p>
        </a>
    </div>
    <div class="shimmer{% if done %} short{% endif %}">
        <form action="#b" method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <div class="form-box">{% block solution2 %}{% endblock %}</div>
        </form>
    </div>
</section>

{% if done %}
<section class="section" id="complete">
    <form class="form-box" id="access" action="/access" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <input type="hidden" name="num" value="{{ obscure_post(num) }}">
        <button class="access-button">Access Discussion Channel</button>
    </form>
</section>
{% endif %}
{% endif %}

<script src="{{ url_for('static', filename='js/cooldown.js') }}" defer></script>

{% endblock %}

app/templates/champions.html
{% extends "default.html" %}

{% block title %} Challenge Champions {% endblock %}

{% block main %}
<section class="section" id="announcement">
  <div class="img-container">
    <img src="{{ url_for('static', filename='images/good_job.png') }}" alt="Congratulations Image">
  </div>
  <div>
    <h2>Congratulations</h2>
    <h3>{{ year }} Champions</h3>
    <p>everyone who completed both parts of all 10 weeks!</p>

    <ul>
    {% for i in range(champions|length) %}
      <li>
        {% if githubs[i] %}
        <a href="https://github.com/{{ githubs[i] }}" target="_blank" rel="noopener noreferrer nofollow" >
          {{ champions[i] }} <i class="devicon-github-original"></i>
        </a>
        {% else %}
        <span class="false-link">
            {{ champions[i] }}
        </span>
        {% endif %}
      </li>
    {% endfor %}
    </ul>
  </div>
</section>
<section class="section" id="all_scores">
  <div id="score-dialog-root"></div>
  <div>
    <h2>All Progress</h2>
    <table>
      <tr>
        <td>1</td><td>2</td><td>3</td><td>4</td><td>5</td>
        <td>6</td><td>7</td><td>8</td><td>9</td><td>10</td>
        <td style="border-right:none; text-align:center;">User</td>
      </tr>
    {% for item in all_data %}
    <tr>
      {% for week in item.progress %}
        <td>
        {%- for c in week -%}
          <span class="{{ 'off' if c == '☆' else 'on' }} lg">{{ c }}</span>
        {%- endfor -%}
        </td>
      {% endfor %}
      <td style="border-right:none; text-align:left;">
        <span class="b {{ 'false-link' if item.id == session.get('user_data', {}).get('id') else '' }}">
          {{ item.name }}
        </span>
      </td>
    </tr>
    {% endfor %}
    </table>
  </div></br>
  <p>
    <button onclick="location.href='/'">
      Home
    </button>
  </p>
</section>
{% endblock %}

app/templates/default.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Practical Python Code Adventure</title>
    {%- for style in css_files %}
    <link href="{{ url_for('static', filename='style/' ~ style ~ '.css') }}" rel="stylesheet" type='text/css'>
    {%- endfor %}
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
          rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" rel="stylesheet" type='text/css'>
    {%- for b in borders %}
    <link as="image" href="{{ url_for('static', filename='images/border_bg/' ~ b ~ '.png') }}" rel="preload"
          type="image/png">
    {%- endfor %}
    <link href="{{ url_for('static', filename='favicon.svg') }}" rel="icon" type="image/svg+xml"/>
    <link href="{{ url_for('static', filename='favicon.ico') }}" rel="icon"/>
</head>
<body>
<a class="skip-link" href="#main-content">Skip to Main content</a>

<nav class="navbar">
    <div class="nav">
        {% if request.endpoint != 'main.release' %}
        <a href="{{ url_for('main.index') }}">
            <span class="material-symbols-outlined">
                home
            </span>
            <span class="nav-text">Home</span>
        </a>
        {% endif %}
        {% if request.endpoint == 'main.release' %}
        <div class="false-link year-menu">
            <span class="material-symbols-outlined">
                calendar_clock
            </span>
            <span class="nav-text">{{ year }}</span>
            <div class="dropdown">
                <a href="{{ url_for('main.release', year=2026) }}"><p><span>2026</span></p></a>
                <a href="{{ url_for('main.release', year=2025) }}"><p><span>2025</span></p></a>
            </div>
        </div>
        {% endif %}
        {% if request.endpoint != 'routes.how_to' %}
        <a href="{{ url_for('routes.how_to') }}">
            <span class="material-symbols-outlined">
                help
            </span>
            <span class="nav-text">How-To</span>
        </a>
        {% endif %}
        {% if request.endpoint != 'routes.champions' %}
        <a href="{{ url_for('routes.champions') }}">
            <span class="material-symbols-outlined">
                trophy
            </span>
            <span class="nav-text">Champions</span>
        </a>
        {% endif %}
        {% if request.endpoint != 'routes.gratitude' %}
        <a href="{{ url_for('routes.gratitude') }}">
            <span class="material-symbols-outlined">
                favorite
            </span>
            <span class="nav-text">Gratitude</span>
        </a>
        {% endif %}
        {% if request.endpoint != 'routes.sponsor' %}
        <a href="{{ url_for('routes.sponsor') }}">
            <span class="material-symbols-outlined">
            star_shine
            </span>
            <span class="nav-text">Sponsors</span>
        </a>
        {% endif %}
        <a href="{{ url_for('auth.pre_login') }}">
            <div class="user-menu">
                {% if session.get("user_data") %}
                {% if img.startswith('http') %}
                {% set img_src = img %}
                {% else %}
                {% set img_src = url_for('static', filename='images/no_img.png') %}
                {% endif %}
                <img alt="Logout" src="{{ img_src }}">
                <span class="material-symbols-outlined user-action">emoji_people</span>
                <span class="user-action">Logout</span>
                {% else %}
                <span class="material-symbols-outlined user-label">emoji_people</span>
                <span class="user-label">Guest</span>
                <span class="material-symbols-outlined user-action">emoji_people</span>
                <span class="user-action">Login</span>
                {% endif %}
            </div>
        </a>
    </div>
</nav>

<header class="section">
    <h1>{% block title %}{% endblock %}</h1>
</header>

<main id="main-content">
    {% block main %}
    {% endblock %}
</main>

</body>
</html>

app/templates/gratitude.html
{% extends "default.html" %}

{% block title %} Thank You! {% endblock %}

{% block main %}
<section class="section" id="announcement">
  <div class="img-container">
    <img src="{{ url_for('static', filename='images/gratitude.png') }}" alt="Thank You Image">
  </div>
  <div>
    <h2>I am grateful to my community for their support.</h2>
    <h3>About This Project</h3>
    <p>
      All challenges were thought up by me,
      <a href="https://github.com/JefeThePug">JefeThePug</a>.
      Though inspiration for individual challenges has come from
      a number of sources.
    </p>
    <p>
      The initial inspiration for this project comes from
      <a href="https://adventofcode.com/">Advent of Code</a>
      created by Eric Wastl.
    </p><br>
    <p class="b i">
      Special thanks are due to
    </p>
    <hr>
    <ul>
      <li>
        <a href="https://github.com/Makaze">makaze
          <i class="devicon-github-original"></i></a>
        for beta testing and advice with the 2025 challenges
      </li>
      <li>
        <a href="https://github.com/max-min-median/">max_min_median
          <i class="devicon-github-original"></i></a>
        for beta testing and advice with the 2025 challenges
      </li>
      <li>
        <span class="false-link">_zadok_</span>
        for beta testing and advice with the 2025 challenges
      </li>
    </ul>
    <hr>
    <ul>
      <li>
        <a href="https://github.com/algmyr">algmyr
          <i class="devicon-github-original"></i></a>
        for beta testing the 2026 challenges
      </li>
      <li>
        <a href="https://github.com/ThobiWanKenobi">thobias
          <i class="devicon-github-original"></i></a>
        for beta testing the 2026 challenges
      </li>
    </ul>
    <hr>
    <p class="b i">
      Special thanks are also due to
    </p>
    <ul>
      <li>
        <a href="https://github.com/Xarlos89">.xarlos
          <i class="devicon-github-original"></i></a>
        for creating the Practical Python Discord server
        and hosting this website
      </li>
    </ul>
  </div>
</section>
<section class="section" id="advertise">
  <div>
    <h3>Seeking Volunteers</h3>
    <p>
      I am currently seeking volunteers for
    </p>
    <ul>
      <li><span class="b">Beta Testers</span> for future challenges</li>
      <li>An <span class="b">illustrator</span> for the landing pages' theme images</li>
    </ul>
    <p>
      If you enjoy this project and want to help me grow it into
      something great, you can <a href="mailto:jefethepug@protonmail.com">
      email</a> me.
    </p></br>
    <p>
      <button onclick="location.href='/'">
        Home
      </button>
    </p>
  </div>
</section>
{% endblock %}

app/templates/how_to.html
{% extends "default.html" %} {% block title %} Instructions {% endblock %} {%
block main %}
<section class="section" id="announcement">
  <div class="img-container">
    <img
      src="{{ url_for('static', filename='images/how_to.png') }}"
      alt="How-To Image"
    />
  </div>
  <div>
    <h2>Welcome to Practical Python Code Adventure</h2>
    <h3>Concept</h3>
    <p>
      A ten-week-long event is held every year. For each week during these
      events, one challenge with two parts is released. In most cases, Part 1 is
      a bit easier, and Part 2 will either be a continuation of Part 1, a
      variation on the concept, or a similar concept in the same realm of
      problem-solving.
    </p>
    <p>
      Each part has its own separate solutions and puzzle inputs, unless
      otherwise indicated.
    </p>
    <h3>Puzzle Inputs</h3>
    <p>
      Each challenge has at least one file that must be used to arrive at the
      correct solution. Usually, this is a text file, but other types of files
      may also be used. Additionally, there may be supplemental images to solve
      the puzzle which can also be downloaded. It is up to you to read this data
      into your own code for each challenge. For each required puzzle input, you
      will see text, indicating it can be downloaded, which looks like this...
    </p>
    <p class="main lg">[ click to get input ]</p>
    <h3>Solutions</h3>
    <p>
      This site offers no online IDE or Python Interpreter. You should write any
      code used to deduce the solutions on your own machine using the downloaded
      puzzle input files. Each challenge has exactly one correct solution for
      each of its two parts, which can be obtained using the puzzle input and
      implementing the correct algorithm hinted in the text of the problem.
    </p>
    <p>
      The solutions will always be text and should be copied and pasted into the
      solution form on the site for submission. Make sure not to leave off any
      part of it. For Part 1, if the correct solution is submitted, you will
      immediately be able to view Part 2 of the challenge. For Part 2, if the
      correct solution is submitted, and you are logged in with Discord, you
      will be awarded a congratulatory screen with a link to the private
      discussion channel for that challenge in the Practical Python server.
    </p>
    <p>
      Practical Python also offers a public discussion channel for help if you
      are struggling with a challenge. However, please be fair to all and avoid
      posting the solutions to any challenges there. While there is no real
      penalty for cheating or sharing the answer, it does ruin the fun.
    </p>
    <h3>Progress</h3>
    <p>
      On the main page, your progress with the challenges is indicated using
      progress icons:
    </p>
    <p>
      {% for condition in ("off", "on") %}
      <span class="material-symbols-outlined icon {{ condition }}">
        {{ ICONS[year]["a-icon"] }}
      </span>
      <span class="material-symbols-outlined icon {{ condition }}">
        {{ ICONS[year]["b-icon"] }}
      </span>
      {% endfor %}
    </p>
    <p>
      These icons will light up when you have completed each part of the
      challenge:<br />the
      <span class="material-symbols-outlined icon on">
        {{ ICONS[year]["a-icon"] }}
      </span>
      {{ ICONS[year]["a-text"] }} for Part 1 and the
      <span class="material-symbols-outlined icon on">
        {{ ICONS[year]["b-icon"] }}
      </span>
      {{ ICONS[year]["b-text"] }} for Part 2.
    </p>
    <p>
      When you are logged in with your Discord account, this progress is saved
      in a database. This allows you to keep your progress across multiple
      browsers and computers indefinitely. If you choose not to log into
      Discord, your progress is stored via browser cookies and cannot be carried
      over to a different browser. Additionally, your progress cannot be relied
      upon to remain for any amount of time, subject to your own cookie settings
      and this server's session. Plan ahead to remember the previously completed
      challenge solutions while using this site as a Guest account, in case you
      lose your progress.
    </p>
  </div>
</section>
<section class="section" id="closing">
  <p>
    As always, the staff at Practical Python are happy to help if you are
    experiencing any difficulties. Please contact them via the
    <a href="https://discord.gg/H2V9Fd2sfD" target="_blank"> Discord server</a>.
  </p>
  <p>Good luck and happy coding!</p>
  <p>
    <button onclick="location.href = '/'">Home</button>
  </p>
</section>
{% endblock %}

app/templates/index.html
{% extends "default.html" %} {% block title %} Practical Python Code Adventure
{% endblock %} {% block main %}
<section class="section" id="logo">
  <div class="logo-container">
    <img
      alt="Illustration of Captain Xarlos"
      src="{{ url_for('static', filename='images/' ~ year ~ '/index/logo.png') }}"
    />
  </div>
  {% include year ~ '/index_content.html' %}
</section>

<section class="section" id="challenges">
  <ul>
    {% for week in range(1, num + 1) %}
    <li>
      <a
        href="{{ url_for('challenge.challenge', year=year, obs_num=obfuscate(year, week)) }}"
        >Week&nbsp;{{ "%2d" | format(week) }}</a
      >
      <span
        class="material-symbols-outlined icon {{ ('off', 'on')[rockets[week - 1][0]] }}"
      >
        {{ ICONS[year]["a-icon"] }}
      </span>
      <span
        class="material-symbols-outlined icon {{ ('off', 'on')[rockets[week - 1][1]] }}"
      >
        {{ ICONS[year]["b-icon"] }}
      </span>
    </li>
    {% endfor %}
  </ul>
  {% if num < 10 %} More Challenges Coming Soon… {% endif %}
</section>

{% endblock %}

app/templates/link_complete.html
{% extends "default.html" %}

{% block title %}
Access Granted
{% endblock %}

{% block main %}
<section class="section" id="announcement">
    <div class="img-container">
        {% set path = ['images', year, '%02d'|format(num), num ~ '.mp4'] | join('/') %}
        {% set img_src = url_for('static', filename=path) %}
        <video autoplay muted playsinline id="vid" class="fill">
            <source src="{{ img_src }}" type="video/mp4">
        </video>
        <span id="replay-btn" class="material-symbols-outlined" style="cursor:pointer">
            replay
        </span>
        <script src="{{ url_for('static', filename='js/replay.js') }}" defer></script>
    </div>
    <div>
        <p>
            Well done! You solved both parts of Challenge {{ num }} and have gained
            access to {{ year }}'s Week {{ num }} Discussion Channel.
        </p>
        <p>
            Feel free to share your code and discuss what led you to the solutions
            for both Part 1 and Part 2 there.
        </p>
        <p>
            <a class="access-button" href="discord://discordapp.com/channels/{{ guild }}/{{ channel }}">
                Visit the channel now
            </a>
            <span>or</span>
            <button onclick="location.href='/'">
                Go back to solve more challenges
            </button>
        </p>
    </div>
</section>
<section class="section" id="easter-egg">
    <div>
        <p class="sm">
            <span class="material-symbols-outlined icon egg">egg</span>
            <span class="egg">{{ egg|safe }}</span>
        </p>
    </div>
</section>
{% endblock %}

app/templates/login.html
{% extends "default.html" %}

{% block title %} Login {% endblock %}

{% block main %}
<section class="section" id="announcement">
  <div class="img-container">
    <img src="{{ url_for('static', filename='images/login.png') }}" alt="Login Image">
  </div>
  <div>
    <h2>Login with Discord</h2>
    <h3>What this means:</h3>
    <p>
      Logging into your Discord account will save your progress with completed challenges on this site.
      Additionally, this app gives you access to private discussion threads for each challenge
      within the Practical Python server.
    </p>
    <p>
      If you are not a member of the Practical Python server, this app will join that server for you. This
      provides a forum for discussing your solutions and viewing the solutions of other challengers.
    </p>
    <p>
      Because of this, the login prompt will require you to allow this app to control joining servers
      automatically for you. Practical Python does not store any of your data in its database apart
      from your username/id and your progress with these challenges. We promise that your personal
      information is never kept on file.
    </p>
    <button onclick="location.href='/login'">Login</button>
  </div></br>
  <p>
    <button onclick="location.href='/'">
      Home
    </button>
  </p>
</section>
{% endblock %}

app/templates/logout.html
{% extends "default.html" %}

{% block title %} Logout {% endblock %}

{% block main %}
<section class="section" id="announcement">
    <div class="img-container">
        <img src="{{ url_for('static', filename='images/logout.png') }}" alt="Logout Image">
    </div>
    <div>
        <h2>Logout of Your Account</h2>
        <div>
            <h3>Are you sure you want to Logout?</h3>
            <button onclick="location.href='/logout'">Yes</button>
            <button onclick="location.href='/'">No</button>
        </div>
    </div></br>
    <p>
        <button onclick="location.href='/'">
            Home
        </button>
    </p>
</section>
{% endblock %}